"""add_last_seen_to_users_table

Revision ID: 1f330961caac
Revises: 13a29ef2e4c0
Create Date: 2026-07-20 16:41:17.137113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f330961caac'
down_revision: Union[str, None] = '13a29ef2e4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_reactions',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_message_user_emoji')
    )
    op.create_index(op.f('ix_message_reactions_id'), 'message_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_message_reactions_message_id'), 'message_reactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_reactions_user_id'), 'message_reactions', ['user_id'], unique=False)
    op.add_column('conversations', sa.Column('pinned_message_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversations_pinned_message_id'), 'conversations', ['pinned_message_id'], unique=False)
    op.create_foreign_key('fk_conversations_pinned_message_id', 'conversations', 'messages', ['pinned_message_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('messages', sa.Column('reply_to_message_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    op.add_column('messages', sa.Column('attachment_name', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('attachment_size', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('attachment_type', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_column('messages', 'thumbnail_url')
    op.drop_column('messages', 'attachment_type')
    op.drop_column('messages', 'attachment_size')
    op.drop_column('messages', 'attachment_name')
    op.drop_column('messages', 'attachment_url')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'reply_to_message_id')
    op.drop_constraint('fk_conversations_pinned_message_id', 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_pinned_message_id'), table_name='conversations')
    op.drop_column('conversations', 'pinned_message_id')
    op.drop_index(op.f('ix_message_reactions_user_id'), table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_message_id'), table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_id'), table_name='message_reactions')
    op.drop_table('message_reactions')
    # ### end Alembic commands ###
