"""add_instagram_reels

Revision ID: 29cd4bcead61
Revises: c3791d4767e6
Create Date: 2026-07-08 18:01:15.646594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29cd4bcead61'
down_revision: Union[str, None] = 'c3791d4767e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_profiles', sa.Column('instagram_reels', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_profiles', 'instagram_reels')
    # ### end Alembic commands ###
