"""add_artist_city_state

Revision ID: 480018cab2a6
Revises: 8f4d17d6bad4
Create Date: 2026-07-14 16:34:28.951291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480018cab2a6'
down_revision: Union[str, None] = '8f4d17d6bad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_profiles', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('artist_profiles', sa.Column('state', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_artist_profiles_city'), 'artist_profiles', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_profiles_city'), table_name='artist_profiles')
    op.drop_column('artist_profiles', 'state')
    op.drop_column('artist_profiles', 'city')
    # ### end Alembic commands ###
