"""add_notification_type_and_link

Revision ID: 4a0e888438c4
Revises: 9f956581e2de
Create Date: 2026-07-19 11:01:26.553048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0e888438c4'
down_revision: Union[str, None] = '9f956581e2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_audit_logs',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_audit_logs_booking_id'), 'booking_audit_logs', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_audit_logs_id'), 'booking_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_booking_audit_logs_user_id'), 'booking_audit_logs', ['user_id'], unique=False)
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'link')
    op.drop_column('notifications', 'notification_type')
    op.drop_index(op.f('ix_booking_audit_logs_user_id'), table_name='booking_audit_logs')
    op.drop_index(op.f('ix_booking_audit_logs_id'), table_name='booking_audit_logs')
    op.drop_index(op.f('ix_booking_audit_logs_booking_id'), table_name='booking_audit_logs')
    op.drop_table('booking_audit_logs')
    # ### end Alembic commands ###
