"""add_venue_owner_details_fields

Revision ID: 4f818e37a292
Revises: 56bce48b861d
Create Date: 2026-07-08 18:27:08.179739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f818e37a292'
down_revision: Union[str, None] = '56bce48b861d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('business_name', sa.String(length=150), nullable=True))
    op.add_column('venues', sa.Column('contact_details', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'contact_details')
    op.drop_column('venues', 'business_name')
    # ### end Alembic commands ###
