"""add_venue_registration_fields

Revision ID: 56bce48b861d
Revises: d251fbf76528
Create Date: 2026-07-08 18:24:33.621190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bce48b861d'
down_revision: Union[str, None] = 'd251fbf76528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('min_capacity', sa.Integer(), nullable=False))
    op.add_column('venues', sa.Column('venue_type', sa.String(length=50), nullable=True))
    op.add_column('venues', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.add_column('venues', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('venues', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('venues', sa.Column('google_map_location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'google_map_location')
    op.drop_column('venues', 'country')
    op.drop_column('venues', 'state')
    op.drop_column('venues', 'pincode')
    op.drop_column('venues', 'venue_type')
    op.drop_column('venues', 'min_capacity')
    # ### end Alembic commands ###
