"""add_notifications_foundation_fields

Revision ID: 588015aee28d
Revises: 4a0e888438c4
Create Date: 2026-07-19 11:29:19.642282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588015aee28d'
down_revision: Union[str, None] = '4a0e888438c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('recipient_user_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('recipient_role', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('reference_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('reference_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('notification_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['recipient_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_column('notifications', 'notification_metadata')
    op.drop_column('notifications', 'reference_id')
    op.drop_column('notifications', 'reference_type')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'recipient_role')
    op.drop_column('notifications', 'recipient_user_id')
    # ### end Alembic commands ###
