"""add_registration_fields

Revision ID: 5daef3f2a55a
Revises: 3a5d795e03a2
Create Date: 2026-07-08 17:48:57.003349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5daef3f2a55a'
down_revision: Union[str, None] = '3a5d795e03a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_profiles', sa.Column('display_name', sa.String(length=150), nullable=True))
    op.add_column('artist_profiles', sa.Column('mobile_number', sa.String(length=30), nullable=True))
    op.add_column('artist_profiles', sa.Column('years_of_experience', sa.Integer(), nullable=False))
    op.add_column('artist_profiles', sa.Column('profile_image', sa.String(length=255), nullable=True))
    op.add_column('artist_profiles', sa.Column('cover_image', sa.String(length=255), nullable=True))
    op.add_column('artist_profiles', sa.Column('band_type', sa.String(length=50), nullable=False))
    op.add_column('artist_profiles', sa.Column('total_members', sa.Integer(), nullable=False))
    op.add_column('artist_profiles', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('artist_profiles', sa.Column('travel_radius', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('artist_profiles', sa.Column('travel_charges', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('artist_profiles', sa.Column('min_booking_hours', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('artist_profiles', sa.Column('max_booking_hours', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('artist_profiles', sa.Column('equipment', sa.JSON(), nullable=False))
    op.add_column('artist_profiles', sa.Column('availability', sa.JSON(), nullable=False))
    op.add_column('artist_profiles', sa.Column('youtube_links', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_profiles', 'youtube_links')
    op.drop_column('artist_profiles', 'availability')
    op.drop_column('artist_profiles', 'equipment')
    op.drop_column('artist_profiles', 'max_booking_hours')
    op.drop_column('artist_profiles', 'min_booking_hours')
    op.drop_column('artist_profiles', 'travel_charges')
    op.drop_column('artist_profiles', 'travel_radius')
    op.drop_column('artist_profiles', 'currency')
    op.drop_column('artist_profiles', 'total_members')
    op.drop_column('artist_profiles', 'band_type')
    op.drop_column('artist_profiles', 'cover_image')
    op.drop_column('artist_profiles', 'profile_image')
    op.drop_column('artist_profiles', 'years_of_experience')
    op.drop_column('artist_profiles', 'mobile_number')
    op.drop_column('artist_profiles', 'display_name')
    # ### end Alembic commands ###
