"""update_bookings_relational

Revision ID: 8ab5352e83f2
Revises: f3b3c7e54c9e
Create Date: 2026-07-10 02:38:42.859835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ab5352e83f2'
down_revision: Union[str, None] = 'f3b3c7e54c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_attachments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_attachments_booking_id'), 'booking_attachments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_attachments_id'), 'booking_attachments', ['id'], unique=False)
    op.create_table('booking_notes',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_notes_booking_id'), 'booking_notes', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_notes_id'), 'booking_notes', ['id'], unique=False)
    op.create_table('booking_status_histories',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_role', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_status_histories_booking_id'), 'booking_status_histories', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_status_histories_id'), 'booking_status_histories', ['id'], unique=False)
    op.create_table('booking_timelines',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_timelines_booking_id'), 'booking_timelines', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_timelines_id'), 'booking_timelines', ['id'], unique=False)
    op.add_column('bookings', sa.Column('event_title', sa.String(length=255), nullable=False))
    op.add_column('bookings', sa.Column('event_type', sa.String(length=100), nullable=False))
    op.add_column('bookings', sa.Column('duration', sa.Numeric(precision=4, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('guest_count', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('bookings', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('bookings', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('bookings', sa.Column('state', sa.String(length=100), nullable=False))
    op.add_column('bookings', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('bookings', sa.Column('google_maps_coords', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('special_requests', sa.Text(), nullable=True))
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('bookings', 'timeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('timeline', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('bookings', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('bookings', 'special_requests')
    op.drop_column('bookings', 'google_maps_coords')
    op.drop_column('bookings', 'country')
    op.drop_column('bookings', 'state')
    op.drop_column('bookings', 'city')
    op.drop_column('bookings', 'address')
    op.drop_column('bookings', 'budget')
    op.drop_column('bookings', 'guest_count')
    op.drop_column('bookings', 'duration')
    op.drop_column('bookings', 'event_type')
    op.drop_column('bookings', 'event_title')
    op.drop_index(op.f('ix_booking_timelines_id'), table_name='booking_timelines')
    op.drop_index(op.f('ix_booking_timelines_booking_id'), table_name='booking_timelines')
    op.drop_table('booking_timelines')
    op.drop_index(op.f('ix_booking_status_histories_id'), table_name='booking_status_histories')
    op.drop_index(op.f('ix_booking_status_histories_booking_id'), table_name='booking_status_histories')
    op.drop_table('booking_status_histories')
    op.drop_index(op.f('ix_booking_notes_id'), table_name='booking_notes')
    op.drop_index(op.f('ix_booking_notes_booking_id'), table_name='booking_notes')
    op.drop_table('booking_notes')
    op.drop_index(op.f('ix_booking_attachments_id'), table_name='booking_attachments')
    op.drop_index(op.f('ix_booking_attachments_booking_id'), table_name='booking_attachments')
    op.drop_table('booking_attachments')
    # ### end Alembic commands ###
