"""add_notifications_and_cooldown

Revision ID: 8f4d17d6bad4
Revises: 8ab5352e83f2
Create Date: 2026-07-14 16:28:50.430431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f4d17d6bad4'
down_revision: Union[str, None] = '8ab5352e83f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index('ix_booking_notes_booking_id', table_name='booking_notes')
    op.drop_index('ix_booking_notes_id', table_name='booking_notes')
    op.drop_table('booking_notes')
    op.drop_index('ix_booking_timelines_booking_id', table_name='booking_timelines')
    op.drop_index('ix_booking_timelines_id', table_name='booking_timelines')
    op.drop_table('booking_timelines')
    op.drop_index('ix_booking_status_histories_booking_id', table_name='booking_status_histories')
    op.drop_index('ix_booking_status_histories_id', table_name='booking_status_histories')
    op.drop_table('booking_status_histories')
    op.drop_index('ix_booking_attachments_booking_id', table_name='booking_attachments')
    op.drop_index('ix_booking_attachments_id', table_name='booking_attachments')
    op.drop_table('booking_attachments')
    op.add_column('bookings', sa.Column('timeline', sa.JSON(), nullable=False))
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_column('bookings', 'budget')
    op.drop_column('bookings', 'state')
    op.drop_column('bookings', 'duration')
    op.drop_column('bookings', 'guest_count')
    op.drop_column('bookings', 'country')
    op.drop_column('bookings', 'city')
    op.drop_column('bookings', 'special_requests')
    op.drop_column('bookings', 'event_title')
    op.drop_column('bookings', 'address')
    op.drop_column('bookings', 'event_type')
    op.drop_column('bookings', 'google_maps_coords')
    op.add_column('users', sa.Column('last_verification_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_sent_at')
    op.add_column('bookings', sa.Column('google_maps_coords', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('event_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('special_requests', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('guest_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('duration', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('budget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.alter_column('bookings', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('bookings', 'timeline')
    op.create_table('booking_attachments',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploader_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='booking_attachments_booking_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name='booking_attachments_uploader_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='booking_attachments_pkey')
    )
    op.create_index('ix_booking_attachments_id', 'booking_attachments', ['id'], unique=False)
    op.create_index('ix_booking_attachments_booking_id', 'booking_attachments', ['booking_id'], unique=False)
    op.create_table('booking_status_histories',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('changed_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('changed_by_role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='booking_status_histories_booking_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name='booking_status_histories_changed_by_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='booking_status_histories_pkey')
    )
    op.create_index('ix_booking_status_histories_id', 'booking_status_histories', ['id'], unique=False)
    op.create_index('ix_booking_status_histories_booking_id', 'booking_status_histories', ['booking_id'], unique=False)
    op.create_table('booking_timelines',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by_role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='booking_timelines_booking_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='booking_timelines_created_by_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='booking_timelines_pkey')
    )
    op.create_index('ix_booking_timelines_id', 'booking_timelines', ['id'], unique=False)
    op.create_index('ix_booking_timelines_booking_id', 'booking_timelines', ['booking_id'], unique=False)
    op.create_table('booking_notes',
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('author_role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='booking_notes_author_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='booking_notes_booking_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='booking_notes_pkey')
    )
    op.create_index('ix_booking_notes_id', 'booking_notes', ['id'], unique=False)
    op.create_index('ix_booking_notes_booking_id', 'booking_notes', ['booking_id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
