"""add_social_and_achievements

Revision ID: c3791d4767e6
Revises: 5daef3f2a55a
Create Date: 2026-07-08 17:55:08.826899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3791d4767e6'
down_revision: Union[str, None] = '5daef3f2a55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_profiles', sa.Column('social_links', sa.JSON(), nullable=False))
    op.add_column('artist_profiles', sa.Column('achievements', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_profiles', 'achievements')
    op.drop_column('artist_profiles', 'social_links')
    # ### end Alembic commands ###
