"""add_venue_documents_and_metadata

Revision ID: f3b3c7e54c9e
Revises: fcfca1fabe4e
Create Date: 2026-07-09 01:28:33.516472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b3c7e54c9e'
down_revision: Union[str, None] = 'fcfca1fabe4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('documents', sa.JSON(), nullable=False))
    op.add_column('venues', sa.Column('metadata_fields', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'metadata_fields')
    op.drop_column('venues', 'documents')
    # ### end Alembic commands ###
